# GitHub repository settings for merge behavior
# Note: This requires the GitHub Settings app or repository admin configuration

# Enforce PR number in merge commits
merge_method:
  # Allow only these merge methods
  allowed_methods:
    - rebase
    - squash
  
  # Disable merge commits
  allow_merge_commit: false
  
  # Enable rebase merging
  allow_rebase_merge: true
  
  # Enable squash merging
  allow_squash_merge: true

# Automatic PR title formatting for squash commits
squash_merge_commit_title: "PR_TITLE"
squash_merge_commit_message: "PR_BODY"

# Branch protection rules (requires repo admin)
branch_protection:
  main:
    required_status_checks:
      strict: true
      contexts:
        - "Format Check"
        - "Build and Test (ubuntu-latest, Debug)"
        - "Build and Test (ubuntu-latest, Release)"
        - "Build and Test (macos-latest, Debug)"
        - "Build and Test (macos-latest, Release)"
    enforce_admins: true
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    restrictions: null