#!/bin/bash

# Copyright 2025 Gopher Security, Inc.
# SPDX-License-Identifier: Apache-2.0

# Append (#PR_NUMBER) to the first line of every commit on this branch.
# Usage: ./scripts/add-pr-number.sh <PR_NUMBER> [BASE_BRANCH]
#
# The rest of the message is preserved byte for byte. Earlier versions rewrote
# it with -m, which reflowed or destroyed it in several ways; the generated
# step script below documents what each guard is there for.

set -e

if [ $# -eq 0 ]; then
    echo "Usage: $0 <PR_NUMBER> [BASE_BRANCH]"
    echo "Example: $0 123"
    echo ""
    echo "This script adds (#PR_NUMBER) to all commits since origin/main"
    exit 1
fi

PR_NUMBER=$1
BASE_BRANCH=${2:-origin/main}

# The number is interpolated into a sed replacement and a grep pattern below,
# so anything but digits could alter messages in ways nobody asked for.
case "$PR_NUMBER" in
    ''|*[!0-9]*)
        echo "Error: PR number must be digits, got '$PR_NUMBER'" >&2
        exit 1
        ;;
esac

echo "Adding (#$PR_NUMBER) to commits since $BASE_BRANCH"
echo ""

# Show what will be modified. This must apply the same rule as the rewrite
# below, or the preview lies about what is about to happen.
echo "New commits in this branch (will add PR number to these):"
git log --format='%h %s' "$BASE_BRANCH..HEAD" | while read -r line; do
  if echo "$line" | grep -Eq "\(#$PR_NUMBER\)[[:space:]]*$"; then
    echo "  ✓ $line (already has #$PR_NUMBER)"
  else
    echo "  → $line"
  fi
done
echo ""

read -p "Continue? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
fi

# The per-commit work lives in its own file rather than inline, because
# git rebase --exec rejects a command containing newlines and the logic no
# longer fits on one readable line. It is written into the git directory, not
# the work tree: the rebase checks out a different commit at every step, so a
# script tracked in the repo would vanish under its own feet. It is also left
# in place when the rebase stops, so that git rebase --continue still works.
STEP="$(git rev-parse --git-dir)/add-pr-number-step.sh"

cat > "$STEP" <<'STEP_EOF'
#!/bin/sh
# Rewrite the first line of HEAD's message, preserving every other byte.
# Generated by scripts/add-pr-number.sh; safe to delete.
set -e

PR_NUMBER=$1
MSG="$(git rev-parse --git-dir)/ADD_PR_NUMBER_MSG"
trap 'rm -f "$MSG" "$MSG.new"' EXIT

# Everything after the first truly empty line of the commit object is the
# message. Header continuation lines are always prefixed with a space, so an
# empty line can only be the separator. This holds for multi-line gpgsig and
# mergetag headers, whose embedded blank lines are stored as " ".
git cat-file commit HEAD | sed '1,/^$/d' > "$MSG"

# git refuses to amend to an empty message, so leave such a commit alone rather
# than failing the whole rebase over one nobody meant to tag.
if [ ! -s "$MSG" ]; then
    echo "  skipped (empty commit message)"
    exit 0
fi

first=$(head -n 1 "$MSG")

# Skip only when this exact number is already present. A trailing (#N) holding
# some other number is as likely an issue reference as a PR number, and nothing
# in the text distinguishes them, so it is kept and the PR number is appended
# after it. Trailing whitespace is tolerated so a re-run stays a no-op on a
# subject that happens to end in spaces.
if printf '%s' "$first" | grep -Eq "\(#$PR_NUMBER\)[[:space:]]*\$"; then
    echo "  skipped (already #$PR_NUMBER): $first"
    exit 0
fi

CR=$(printf '\r')
if printf '%s' "$first" | grep -q "$CR\$"; then
    # A CRLF message: appending at end-of-line would put the number after the
    # carriage return, where it renders as though it were on a line of its own.
    sed "1s/$CR\$/ (#$PR_NUMBER)$CR/" "$MSG" > "$MSG.new"
else
    sed "1s/\$/ (#$PR_NUMBER)/" "$MSG" > "$MSG.new"
fi

# --cleanup=verbatim is what stops git collapsing runs of blank lines and
# trimming trailing whitespace. Without it the body survives but is reflowed.
git commit --amend --no-verify --cleanup=verbatim -F "$MSG.new"
STEP_EOF

chmod +x "$STEP"

# Quoted so a path containing spaces cannot split. A non-zero exit from the
# step now stops the rebase, instead of being swallowed and reported as success
# while commits are silently left untagged.
git rebase "$BASE_BRANCH" --exec "'$STEP' '$PR_NUMBER'"

rm -f "$STEP"

echo ""
echo "✅ Done. Commits without a PR number now carry (#$PR_NUMBER);"
echo "   any that already had one were left untouched."
echo ""
echo "To push these changes:"
echo "  git push --force-with-lease"
echo ""
echo "⚠️  Warning: This will rewrite history. Make sure you're on a feature branch!"
