name: Auto Add PR Number

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-commits:
    name: Add PR Number to Commits
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout PR
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
    - name: Check and update commit messages
      id: update-commits
      run: |
        PR_NUMBER="${{ github.event.pull_request.number }}"
        BASE_BRANCH="origin/${{ github.base_ref }}"
        HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
        
        echo "Checking commits in PR #${PR_NUMBER}"
        
        # Get list of commits in this PR
        COMMITS=$(git rev-list ${BASE_BRANCH}..HEAD)
        NEEDS_UPDATE=false
        
        for commit in $COMMITS; do
          MESSAGE=$(git log -1 --pretty=%s $commit)
          # Check if commit message already has a PR number
          if ! echo "$MESSAGE" | grep -q "(#[0-9]\+)$"; then
            echo "Commit $commit needs PR number: $MESSAGE"
            NEEDS_UPDATE=true
          fi
        done
        
        if [ "$NEEDS_UPDATE" = true ]; then
          echo "needs_update=true" >> $GITHUB_OUTPUT
          
          # Create a new branch for the updated commits
          git checkout -b temp-pr-${PR_NUMBER}
          
          # Rebase and add PR numbers
          export PR_NUMBER
          git rebase ${BASE_BRANCH} -x 'git commit --amend -m "$(git log -1 --pretty=%s) (#$PR_NUMBER)"'
          
          # Force push the updated branch
          git push --force-with-lease origin HEAD:${HEAD_BRANCH}
          
          echo "✅ Updated commit messages with PR #${PR_NUMBER}"
        else
          echo "needs_update=false" >> $GITHUB_OUTPUT
          echo "All commits already have PR numbers"
        fi
        
    - name: Comment on PR
      if: steps.update-commits.outputs.needs_update == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          
          const comment = `## ✅ PR Number Added to Commits
          
          I've automatically added \`(#${prNumber})\` to all commit messages in this PR.
          
          This ensures that when using "Rebase and merge", all commits will be properly tagged with the PR number in the main branch history.`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: comment
          });