name: Build Status

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
    - name: Update README badge
      run: echo "Badge will be automatically available at https://github.com/${{ github.repository }}/actions/workflows/ci.yml/badge.svg"