name: CI (macOS)

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    name: Build and Test (macOS)
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        brew update
        brew install cmake
        
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        
    - name: Build
      run: |
        cmake --build build --config Debug -j$(sysctl -n hw.ncpu)
        
    - name: Test
      run: |
        cd build
        ctest -C Debug --output-on-failure --verbose
        
    - name: List all tests
      if: always()
      run: |
        make test-list || true